name: visualboyadvance-m
version: 2.1.8
summary: Nintendo Game Boy Advance Emulator
description: |
  An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.

grade: stable
confinement: strict
base: core22

package-repositories:
  - type: apt
    components: [universe]
    suites: [jammy]
    key-id: 7716412FB5B50060D47CF42B6856E1DB1AC82609
    url: https://repos.codelite.org/wx3.2.1/ubuntu/

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

parts:
  vbam:
    source: https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.1.8.tar.gz
    override-build: |
      snapcraftctl build
      sed -i.bak -e 's|Icon=visualboyadvance-m|Icon=/usr/share/icons/hicolor/scalable/apps/visualboyadvance-m.svg|g' /root/parts/vbam/install/usr/share/applications/visualboyadvance-m.desktop
    plugin: cmake
    stage-packages:
      - libsdl2-2.0-0
      - libsfml-network2.5
      - libsfml-system2.5
      - libnotify4
      - libsm6
      - libopenal1
      - libpng16-16
      - libpulse0
      - zlib1g
      - libgtk-3-0
      - libgl1
      - libglvnd0
      - libglx0
      - libopengl0
      - libwxgtk3.2-0-unofficial

    build-packages:
      - g++
      - gcc
      - make
      - cmake
      - pkg-config
      - git
      - zip
      - libnotify-dev
      - libsdl2-dev
      - libsfml-dev
      - libgtk-3-dev
      - libopenal-dev
      - libwxgtk3.2unofficial-dev
    cmake-parameters:
      - -DENABLE_OPENAL=ON
      - -DENABLE_SDL=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr

apps:
  visualboyadvance-m:
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - opengl
      - joystick
      - raw-usb
      - screen-inhibit-control
      - home
      - removable-media
      - network
      - wayland
      - x11
    command: usr/bin/visualboyadvance-m
    desktop: usr/share/applications/visualboyadvance-m.desktop
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
